modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
    modId="mob_blocks"
    version="${file.jarVersion}"
    displayName="Mob Blocks Mod"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/mod-blocks"
    #logoFile="examplemod.png"
    authors="justAm0dd3r" #optional
    description='''
    A mod that adds blocks for different vanilla mobs.
    '''

[[dependencies.mob_blocks]]
    modId="forge"
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.mob_blocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
